from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as rl_canvas
from datetime import datetime
import qrcode
import os

def _styles():
    styles = getSampleStyleSheet()
    title = ParagraphStyle('Title',
        parent=styles['Heading1'], fontSize=18, leading=24,
        alignment=TA_CENTER, textColor=colors.HexColor("#003366"),
        spaceAfter=12
    )
    subtitle = ParagraphStyle('Subtitle',
        parent=styles['Normal'], fontSize=10, leading=14,
        alignment=TA_CENTER, textColor=colors.HexColor("#666666"),
        spaceAfter=18
    )
    h2 = ParagraphStyle('H2',
        parent=styles['Heading2'], fontSize=14, leading=18,
        textColor=colors.HexColor("#0a1172"), spaceBefore=14, spaceAfter=8
    )
    body = ParagraphStyle('Body',
        parent=styles['Normal'], fontSize=10.5, leading=15,
        alignment=TA_JUSTIFY
    )
    bullet = ParagraphStyle('Bullet',
        parent=styles['Normal'], fontSize=10.5, leading=15, leftIndent=12
    )
    return title, subtitle, h2, body, bullet

def _header_footer(c: rl_canvas.Canvas, doc):
    c.saveState()
    # header
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#003366"))
    c.drawString(doc.leftMargin, A4[1] - 20, "AI Courtroom Assistant Report")
    c.setFillColor(colors.black)
    # footer
    page_num = c.getPageNumber()
    c.setFont("Helvetica", 9)
    c.drawCentredString(A4[0]/2, 15, f"Page {page_num}")
    c.restoreState()

def _make_qr(case_id: str) -> str:
    url = f"http://localhost:8000/case/{case_id}"
    img = qrcode.make(url)
    fname = f"qr_{case_id}.png"
    img.save(fname)
    return fname

def generate_pdf(summary, facts, petition, ipc_list, resources, case_id="case", filename="legal_report.pdf"):
    title, subtitle, h2, body, bullet = _styles()

    doc = SimpleDocTemplate(
        filename, pagesize=A4,
        rightMargin=40, leftMargin=40, topMargin=50, bottomMargin=40
    )

    story = []

    # Title page
    story.append(Paragraph("AI COURTROOM ASSISTANT REPORT", title))
    story.append(Paragraph("Legal Analysis & Documentation", subtitle))
    story.append(Spacer(1, 6))

    # QR
    qr_path = _make_qr(case_id)
    if os.path.exists(qr_path):
        story.append(Image(qr_path, width=70, height=70))
        story.append(Spacer(1, 6))

    # Case meta
    meta = [
        ["Date Generated:", datetime.now().strftime("%d-%m-%Y %H:%M:%S")],
        ["Jurisdiction:", facts.get("Jurisdiction", "Not specified")],
        ["Case Reference:", facts.get("Case Reference", "Not provided")],
    ]
    meta_tbl = Table(meta, colWidths=[110, 360])
    meta_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#f5f5f5")),
        ("BOX", (0,0), (-1,-1), 0.8, colors.gray),
        ("INNERGRID", (0,0), (-1,-1), 0.25, colors.lightgrey),
        ("FONT", (0,0), (-1,-1), "Helvetica", 10)
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 10))

    # Disclaimer
    story.append(Paragraph(
        "<i>This document is generated by an AI assistant for informational purposes only. "
        "It does not constitute legal advice. Please consult a qualified attorney.</i>", body))
    story.append(PageBreak())

    # Table of Contents
    toc = TableOfContents()
    toc.levelStyles = [
        ParagraphStyle(fontName='Helvetica-Bold', name='TOCHeading1', fontSize=12, leftIndent=10, firstLineIndent=-10, spaceBefore=8),
        ParagraphStyle(fontName='Helvetica', name='TOCHeading2', fontSize=10, leftIndent=20, firstLineIndent=-10, spaceBefore=4),
    ]
    story.append(Paragraph("Table of Contents", h2))
    story.append(toc)
    story.append(PageBreak())

    # Summary
    story.append(Paragraph("<b>1. Simplified Summary</b>", h2))
    story.append(Paragraph(summary or "Not available", body))
    story.append(Spacer(1, 6))

    # Key Facts
    story.append(Paragraph("<b>2. Key Facts of the Case</b>", h2))
    # Render facts as bullet paragraphs
    for k, v in facts.items():
        if isinstance(v, list):
            val = ", ".join(v) if v else "Not detected"
        else:
            val = v if v else "Not detected"
        story.append(Paragraph(f"<b>{k}:</b> {val}", body))
    story.append(Spacer(1, 6))

    # IPC sections
    if ipc_list:
        story.append(Paragraph("<b>3. Applicable IPC Sections</b>", h2))
        data = [["Section", "Description", "Severity"]]
        for i in ipc_list:
            data.append([i["section"], i["description"], i.get("severity", "Low")])
        ipc_tbl = Table(data, colWidths=[70, 320, 80])
        ipc_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#003366")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.whitesmoke),
            ("FONT", (0,0), (-1,0), "Helvetica-Bold", 10),
            ("FONT", (0,1), (-1,-1), "Helvetica", 10),
            ("GRID", (0,0), (-1,-1), 0.6, colors.grey),
            ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ]))
        story.append(ipc_tbl)
        story.append(Spacer(1, 6))

    # Draft petition
    story.append(Paragraph("<b>4. Draft Petition</b>", h2))
    for para in (petition or "").split("\n"):
        p = para.strip()
        if p:
            story.append(Paragraph(p, body))
    story.append(Spacer(1, 6))

    # Resources
    story.append(Paragraph("<b>5. Legal Aid Resources</b>", h2))
    res_data = [["Authority", "Helpline"]]
    for r in resources:
        res_data.append([r.get("Authority", ""), r.get("Helpline", "")])
    res_tbl = Table(res_data, colWidths=[300, 170])
    res_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1a237e")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.whitesmoke),
        ("FONT", (0,0), (-1,0), "Helvetica-Bold", 10),
        ("FONT", (0,1), (-1,-1), "Helvetica", 10),
        ("GRID", (0,0), (-1,-1), 0.6, colors.grey),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
    ]))
    story.append(res_tbl)

    # Build with header/footer
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)

    # cleanup QR
    try:
        os.remove(qr_path)
    except Exception:
        pass

    return filename
